name: task_manager
description: "Task manager project for ostad batch eleven/task_manager"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.0-216.1.beta


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  pin_code_fields: ^8.0.1
  image_picker: ^1.2.0
  http: ^1.5.0
  logger: ^2.6.1
  email_validator: ^3.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/

